-- Configuration
CREATE SCHEMA adv_db AUTHORIZATION adv_db_user;
GRANT ALL PRIVILEGES ON SCHEMA adv_db TO adv_db_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA adv_db GRANT ALL PRIVILEGES ON TABLES TO adv_db_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA adv_db GRANT ALL PRIVILEGES ON SEQUENCES TO adv_db_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA adv_db GRANT ALL PRIVILEGES ON FUNCTIONS TO adv_db_user;