name: Migrate Database

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  migrate:
    name: Apply migrations to production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ariga/setup-atlas@v0

      - name: Apply migrations
        env:
          ATLAS_DB_URL: ${{ secrets.ATLAS_DB_URL }}
        run: atlas migrate apply --env prod
